Repository PeopleForBikes/brokenspoke, pull requests merged in 2023-02, with the labels that each got.

#69 Fix spacing in brochure templates
  .github/workflows/docs.yml
  assets/brochures/template-brochure-pg1-v23.1.svg
  assets/brochures/template-brochure-pg2-v23.1.pdf
  assets/brochures/template-brochure-pg2-v23.1.svg
  bnacore/src/combine.rs
  docs/content/docs/spokes/appender.md
  pipelines/brochures/src/main.rs
  spokes/src/appender.rs
Labels: size/XL

#66 [bundler] Improve the file name parsing
  bnacore/src/bundle.rs
  incubator/bnapi/api/examples/seeder.rs
  incubator/bnapi/api/src/main.rs
Labels: size/L

#72 Fix Python function argument order
  bnacore/src/scorecard.rs
Labels: size/XS

#71 Rename assets
  assets/visuals/logo-bna-full-1015×596.png
  assets/visuals/logo-bna-full-dark-white-text-1015×597.png
  assets/visuals/logo-pfb-no-text-square.svg
  assets/visuals/template-scorecard-pg1-v23.1.svg
  assets/visuals/template-scorecard-pg2-v23.1.pdf
  assets/visuals/template-scorecard-pg2-v23.1.svg
  assets/visuals/template-scorecard-v22.4.svg
  pipelines/brochures/src/main.rs
Labels: size/XS

#73 fix bundler
  assets/city_ratings/city_ratings_2022_v7_sample.csv
  bnacore/Cargo.toml
  bnacore/src/bundle.rs
  pipelines/brochures/src/main.rs
  spokes/src/bundler.rs
Labels: size/M

#59 Update brochure pipeline
  pipelines/brochures/src/main.rs
Labels: size/XS

#77 Update Rust GitHub actions
  .github/workflows/bnacore.yml
  .github/workflows/incubator.yml
  .github/workflows/pipelines-brochures.yml
  .github/workflows/pipelines-retrieve.yml
  .github/workflows/spokes.yml
Labels: size/L

#78 Fix incubator projects
  .github/workflows/spokes.yml
  incubator/bnapi/migration/src/m20220101_000001_create_table.rs
Labels: size/S
